assembly-informational-format: '{NuGetVersion}'
mode: ContinuousDeployment
branches:
  master:
    tag: s
  releases?[/-]:
    tag: rc
  features?[/-]:
    tag: a-{BranchName}
    increment: Minor
  (pull|pull\-requests|pr)[/-]:
    tag: a-pr-{BranchName}
  hotfix(es)?[/-]:
    tag: rc
  support[/-]:
    tag: s
  dev(elop)?(ment)?$:
    tag: b
